### ISSUE TITLE
No error returned if signInWithEmailAndPassword is used with bad email or password

### ISSUE THREAD

**Issue by XavierSATTLER** [armand1m/react-with-firebase-auth#44]
**Describe the bug**
I tried to use `signInWithEmailAndPassword` with emails that were not registered in my Google Identity Platform or emails that were registered but with wrong password. I can see an error 400 in the network developer tool but the `error` object remains empty.

**To Reproduce**
Setup a new react project with firebase and react-with-firebase-auth, as well as in your google cloud console + firebase console.
In Google Identity Platform, create a test user.
Use `signInWithEmailAndPassword` with a random email.
Use `signInWithEmailAndPassword` with your test email but a raondom password.
If you console.log the `error`, it is still undefined.

**Expected behavior**
`error` object shall tell me either "Wrong email" or "Wrong password"

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Browser Firefox
 - Version: 69.0.3-1

Thanks !!

**Comment by armand1m** [comment]
I'll check this today as well

**Comment by armand1m** [comment]
Fixed on 1.3.1 😄

**Comment by tengis** [comment]
This seems like reverted on 1.3.2 but 1.3.1 still works fine.
