### ISSUE TITLE
Expose loading state

### ISSUE THREAD

**Issue by mikefrancis** [armand1m/react-with-firebase-auth#46]
First of all, thanks for making this!

I have it set up and working however I get a few seconds of showing the "sign up" button before the `user` gets populated and then I show a different component to logged in users.

It would be great if there was (like `error`) there was a `loading` which could be used to determine if data fetching is happening in the background,  rather than having the 2 binary logged in/logged out states.

If this is already possible using a combination of the existing state then I'd really appreciate an example.

Cheers!

**Comment by armand1m** [comment]
Thank you @mikefrancis <3
