### ISSUE TITLE
Loading is true by default

### ISSUE THREAD

**Issue by gsouf** [armand1m/react-with-firebase-auth#49]
**Case 1**
After the component mounts, and before any action is taken then `loading` is set to true. 
It's set to false only after a successful attempt to login.

**Case 2**
After the component mounts, if the user is already logged in then `loading` is set to true. It remains true forever.

**Expected behavior**
`loading` is set to true only when a login operation is being performed.

**Comment by Ahmdrza** [comment]
I am facing same issue. Loading value doesn't change so we can't wait for response and render component after the response. It should be set to `false` after response is done.

**Comment by armand1m** [comment]
hummm I"ll need some time to dig into this, as this functionality was merged by a PR from another person

probably will add more unit tests for this to ensure it works properly

**Comment by Ahmdrza** [comment]
Can I look into this and discuss solution and submit PR?

**Comment by armand1m** [comment]
@Ahmdrza feel free to do so! much appreciated hehe

**Comment by SharadKumar** [comment]
@Ahmdrza @armand1m I just implemented this on a sample code and it is the case and not as expected. Looking forward to your PR.

**Comment by Ahmdrza** [comment]
@SharadKumar I haven't worked on it yet due to some work load.

**Comment by Xiphe** [comment]
I'm also having this issue. Let me know when I can help

**Comment by armand1m** [comment]
I started fixing this today as I got some time

**Comment by armand1m** [comment]
Just released the fix on v 1.3.1, feel free to reopen if you still have any issues
