### ISSUE TITLE
signIn Promises

### ISSUE THREAD

**Issue by jynnie** [armand1m/react-with-firebase-auth#65]
Were Promises removed from 1.3.0 to 1.3.2? The below code works for me in 1.3.0, but throws the error "signInWithGoogle is undefined" in 1.3.2 (but without the `.then` throws no error).

`signInWithGoogle().then(res => handleSignIn(res));`

 Either ways, it signs in with the Provider, just doesn't execute `handleSignIn` in 1.3.2

**Comment by armand1m** [comment]
Hey, yes, signIn method calls were supposed to be plain `void` functions since the user prop is automatically updated once the signIn is successful.

Can you share more about your use case? Maybe there is a different way to achieve what you want.

Otherwise, I can consider bringing promises back again, but am curious about your specific use case.

**Comment by jynnie** [comment]
Yeah, I am updating lastSignIn of user in my database after the promise is resolved. If there's another way to do it, would love to know. C:

**Comment by armand1m** [comment]
well, you could also make use of `React.useEffect` with the user as a dependency and update it there but I feel like it would be too much overhead.

Will bring the promises back in the next patch, should be out today

**Comment by jynnie** [comment]
ah, not too familiar with the native auth listener, would that work without a server? (my app is just Firebase + React)

Regardless, thank you! The promise feels more intuitive to me haha

**Comment by armand1m** [comment]
@jynnie yes it would work just fine, yet inside of the component rendering phase it would be more cumbersome than it should be.

I still haven't got the time to come back on this, so sorry! Will try to dedicate some time this week for this.
