### ISSUE TITLE
Pass Unrelated Props Through to the Wrapped Component

### ISSUE THREAD

**Issue by dalibor-123** [armand1m/react-with-firebase-auth#67]
It looks like the wrapper component does not respect convention from React docs: https://reactjs.org/docs/higher-order-components.html#convention-pass-unrelated-props-through-to-the-wrapped-component

**Comment by armand1m** [comment]
actually, it does: https://github.com/armand1m/react-with-firebase-auth/blob/master/src/index.tsx#L173

are you running into some issue?

**Comment by dalibor-123** [comment]
Hello, I eventually realized that it wasn't the case so I closed the issue. I did encounter a problem but it turned out to be completely unrelated to this repo. Thank you so much for caring anyway! :-)
