### ISSUE TITLE
Mostly a thank you, also seems to need Typescript's strict turned off

### ISSUE THREAD

**Issue by scottschafer** [armand1m/react-with-firebase-auth#93]
First and foremost, thanks. I only wish I'd discovered this before trying to merge in the code from https://github.com/the-road-to-react-with-firebase into my app.

It wasn't immediately obvious to me how to make this work in Typescript. I eventually got it working with this import:
`import withFirebaseAuth, { WrappedComponentProps } from 'react-with-firebase-auth'
`
And then by declaring my app like so:
`
const App = ({
  user,
  error,
  loading,
  setError,
  signOut,
  signInAnonymously,
  signInWithEmailAndPassword,
  signInWithGoogle,
  signInWithGithub,
  createUserWithEmailAndPassword,
}: WrappedComponentProps) => {
`
A very small thing though: your sample code makes this call `setError(null)` and that won't compile unless I set Typescript's strict flag to false. Can you consider changing the definition to `setError: (error: string | null) => void;`?

I could open a PR for this.

**Comment by armand1m** [comment]
Hey, I just upgraded the project configuration and now strict mode is enabled everywhere. You shouldn't have these issues anymore. Thank you for the kind words ❤️
